services:
  build:
    platform: linux/amd64
    build:
      context: .
      pull: true
    working_dir: /app
    volumes:
      - .:/app
    command: ["./gradlew", ":sdk:build", "--no-daemon"]

  test:
    platform: linux/amd64
    build:
      context: .
      pull: true
    working_dir: /app
    volumes:
      - .:/app
    command: ["./gradlew", ":sdk:test", "--no-daemon"]
