services:
  build:
    image: gradle:8.8-jdk17
    working_dir: /app
    volumes:
      - .:/app
    command: gradle :sdk:build --no-daemon
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - JAVA_HOME=/opt/java/openjdk

  test:
    image: gradle:8.8-jdk17
    working_dir: /app
    volumes:
      - .:/app
    command: gradle :sdk:test --no-daemon
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - JAVA_HOME=/opt/java/openjdk
