services:
  build:
    platform: linux/amd64
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: ./gradlew :sdk:build --no-daemon
    environment:
      - ANDROID_HOME=/opt/android-sdk

  test:
    platform: linux/amd64
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: ./gradlew :sdk:test --no-daemon
    environment:
      - ANDROID_HOME=/opt/android-sdk
