import org.gradle.api.tasks.bundling.Zip

plugins {
    id("com.android.library")
    id("org.jetbrains.dokka") version "2.2.0"
    id("org.jlleitschuh.gradle.ktlint") version "14.2.0"
    `maven-publish`
    signing
}

group = "com.assinafy"
// Honor a release-automation -Pversion override and otherwise use the released version.
version = (findProperty("version") as String?)?.takeIf { it.isNotBlank() && it != "unspecified" } ?: "2.0.3"

val okHttpVersion = "5.5.0"
val gsonVersion = "2.14.0"
val coroutinesVersion = "1.11.0"
val junitVersion = "6.1.3"
val assertjVersion = "3.27.7"

android {
    namespace = "com.assinafy.sdk"
    compileSdk {
        version = release(37) {
            minorApiLevel = 0
        }
    }
    buildToolsVersion = "36.0.0"

    defaultConfig {
        minSdk = 21
        buildConfigField("String", "SDK_VERSION", "\"$version\"")
        // No targetSdk here: a library does not own it — the consuming app sets its own targetSdkVersion.
        // consumerProguardFiles ships the Gson keep rules INSIDE the published AAR so they are applied
        // during the consuming app's R8 pass — without this, minified release apps strip model fields.
        consumerProguardFiles("proguard-rules.pro")
        // proguardFiles only matters if this library is ever self-minified (it is not by default);
        // kept for completeness and parity with the consumer rules.
        proguardFiles(
            getDefaultProguardFile("proguard-android-optimize.txt"),
            "proguard-rules.pro",
        )
    }

    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }

    lint {
        abortOnError = true
        warningsAsErrors = true
        // Gradle 9.5 is AGP 9.3's tested baseline. Dependabot tracks version changes without
        // weakening every other lint warning.
        disable += setOf("AndroidGradlePluginVersion", "GradleDependency", "NewerVersionAvailable")
    }
}

dokka {
    dokkaPublications.html {
        moduleName.set("Assinafy Android SDK")
        moduleVersion.set(project.version.toString())
        failOnWarning.set(true)
    }
    dokkaSourceSets.configureEach {
        includes.from("Module.md")
        reportUndocumented.set(true)
        sourceLink {
            localDirectory.set(file("src/main/kotlin"))
            remoteUrl("https://github.com/assinafy/mobile-android-sdk/tree/main/sdk/src/main/kotlin")
            remoteLineSuffix.set("#L")
        }
    }
}

val dokkaJavadocJar by tasks.registering(Jar::class) {
    description = "A Javadoc-compatible HTML API documentation JAR generated by Dokka"
    from(tasks.dokkaGeneratePublicationHtml.flatMap { it.outputDirectory })
    archiveClassifier.set("javadoc")
}

val centralRepositoryDirectory = layout.buildDirectory.dir("central-repository")

publishing {
    publications {
        register<MavenPublication>("release") {
            groupId = project.group.toString()
            artifactId = "assinafy-android-sdk"
            version = project.version.toString()
            afterEvaluate {
                from(components["release"])
            }
            artifact(dokkaJavadocJar)
            pom {
                name.set("Assinafy Android SDK")
                description.set("Kotlin client library for the Assinafy API")
                url.set("https://github.com/assinafy/mobile-android-sdk")
                licenses {
                    license {
                        name.set("MIT License")
                        url.set("https://opensource.org/license/mit")
                        distribution.set("repo")
                    }
                }
                developers {
                    developer {
                        id.set("assinafy")
                        name.set("Assinafy")
                        organization.set("Assinafy")
                        organizationUrl.set("https://assinafy.com.br")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/assinafy/mobile-android-sdk.git")
                    developerConnection.set("scm:git:ssh://git@github.com/assinafy/mobile-android-sdk.git")
                    url.set("https://github.com/assinafy/mobile-android-sdk")
                }
            }
        }
    }
    repositories {
        maven {
            name = "CentralBundle"
            url = centralRepositoryDirectory.get().asFile.toURI()
        }
    }
}

val centralPublishingRequested =
    gradle.startParameter.taskNames.any {
        it.endsWith("centralBundle") || it.endsWith("publishReleasePublicationToCentralBundleRepository")
    }
val signingKey =
    providers.environmentVariable("MAVEN_SIGNING_KEY").orNull
        ?: providers.environmentVariable("MAVEN_SIGNING_KEY_FILE").orNull?.let { file(it).readText() }

signing {
    isRequired = centralPublishingRequested
    useInMemoryPgpKeys(signingKey, providers.environmentVariable("MAVEN_SIGNING_PASSWORD").orNull)
    sign(publishing.publications["release"])
}

tasks.named("publishReleasePublicationToCentralBundleRepository") {
    doFirst { delete(centralRepositoryDirectory) }
}

tasks.register<Zip>("centralBundle") {
    group = "publishing"
    description = "Creates the signed repository bundle accepted by Maven Central"
    dependsOn("publishReleasePublicationToCentralBundleRepository")
    from(centralRepositoryDirectory) {
        exclude("**/maven-metadata.xml*")
    }
    archiveFileName.set("central-bundle.zip")
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation("com.squareup.okhttp3:okhttp:$okHttpVersion")
    implementation("com.google.code.gson:gson:$gsonVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")

    testImplementation("org.junit.jupiter:junit-jupiter:$junitVersion")
    testImplementation("com.squareup.okhttp3:mockwebserver3:$okHttpVersion")
    testImplementation("org.assertj:assertj-core:$assertjVersion")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutinesVersion")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:$junitVersion")
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    // Forward live-integration credentials (when present) to the forked test JVM so the opt-in
    // LiveIntegrationTest can read them via System.getenv. Absent vars leave the tests disabled.
    listOf(
        "ASSINAFY_API_KEY",
        "ASSINAFY_ACCOUNT_ID",
        "ASSINAFY_BASE_URL",
        "ASSINAFY_REQUIRE_LIVE",
        "ASSINAFY_LIVE_WRITES",
        "ASSINAFY_TEST_EMAIL",
        "ASSINAFY_TEST_EMAIL_2",
        "ASSINAFY_SIGNER_ACCESS_CODE",
    )
        .forEach { key -> System.getenv(key)?.let { environment(key, it) } }
}
